/** Standing reminder that this content was generated by an AI model from the student's own data. */
export function AiNotice({ children }: { children: React.ReactNode }) {
  return (
    <p className="rounded-sm bg-surface-2 p-3 text-sm">
      <span aria-hidden>✨ </span>
      <strong className="font-semibold">AI-generated. </strong>
      {children}
    </p>
  );
}

export function ProgressBar({ value, label }: { value: number; label: string }) {
  return (
    <div>
      <div className="flex justify-between text-sm">
        <span>{label}</span>
        <span>{Math.round(value)}%</span>
      </div>
      <div
        role="progressbar"
        aria-label={label}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuenow={Math.round(value)}
        className="mt-1 h-2 overflow-hidden rounded-full bg-surface-2"
      >
        <div
          className="h-full rounded-full bg-accent"
          style={{ width: `${Math.min(100, Math.max(0, value))}%` }}
        />
      </div>
    </div>
  );
}
